### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lafith**
Rectified errors regarding class definitions.

### CODE REVIEW

**Comment by lafith** [comment]
Since there is no 'issues' option with this repository, I am commenting here about an error.
After cloning this repo into the Assets folder of an Unity Project, following error is showing:
Screenshot from 2020-08-25 23-17-12

Pointcloud folder is empty.

Screenshot from 2020-08-25 23-17-24

**Comment by MathiasCiarlo** [comment]
Hi! Please have a look here: https://git-scm.com/book/en/v2/Git-Tools-Submodules, under Cloning a Project with Submodules
 :)

**Comment by lafith** [comment]
I have included the git command for cloning.

**Comment by MathiasCiarlo** [comment]
Sweet! 🚀

**Pull request merged**
